Add sandbox_parameter
openprocurement/openregistry.assets.bounce pull request #37
Opened 2018-06-21 12:14 UTC by MichaelYusko

2018-06-21 13:12 UTC, oleksiyVeretiuk requested changes

2018-06-21 13:12 UTC, oleksiyVeretiuk commented on openregistry/assets/bounce/tests/json_data.py
>  from copy import deepcopy
Я б перемістив ці імпорти на рівень вище, щоб була така структура:
імпорт python бібліотек
імпорт допоміжних бібліотек
імпорти з openprocurement-a

2018-06-21 13:47 UTC, oleksiyVeretiuk approved these changes

2018-06-25 16:23 UTC, leits approved these changes

2018-06-25 16:24 UTC, Leits commented
@MichaelYusko , Travis check не пройшов

2018-06-25 18:39 UTC, MichaelYusko commented
@Leits Yeah, first we need to merge https://github.com/openprocurement/openregistry.assets.core/pull/52 because in this PR we imported `SANDBOX_MODE` constant.

2018-06-27 12:31 UTC, leits approved these changes

2018-06-27 13:07 UTC, merged