Related process
openprocurement/openregistry.assets.bounce pull request #45
Opened 2018-10-23 12:35 UTC by bdmbdsm

2019-01-15 09:56 UTC, leits requested changes

2019-01-15 09:56 UTC, Leits commented on openregistry/assets/bounce/migration.py
> +        if related_lot_id is None:
`relatedLot` не буде присутній у всіх статусах окрім `active` i `complete`: http://assetsbounce.api-docs.registry.ea2.openprocurement.io/en/latest/assetsWorkflow.html

Потрібно добавити перевірку на статус у `_skip_predicate`

2019-01-24 11:05 UTC, oleksiyVeretiuk requested changes

2019-01-24 11:05 UTC, oleksiyVeretiuk commented on openregistry/assets/bounce/models.py
> +        if context['status'] == 'active' and not related_processes:
Чи не краще, зробити перевірку на relatedProcess, який має в собі type Lot, адже по великому рахунку важливе не наявність relatedProcess-ів, а наявність relatedProcess-a, який прив'язаний до лота

2019-01-24 11:05 UTC, oleksiyVeretiuk commented on openregistry/assets/bounce/models.py
> +    relatedLot = StringType()
relatedLot заміняється relatedProcesses, чи не треба його звідси прибрати

2019-01-24 14:28 UTC, bdmbdsm commented on openregistry/assets/bounce/models.py
> +    relatedLot = StringType()
Згоден. Приберу.

2019-01-24 14:30 UTC, bdmbdsm commented on openregistry/assets/bounce/models.py
> +        if context['status'] == 'active' and not related_processes:
Правильно, - виправлю.

2019-01-24 14:37 UTC, bdmbdsm commented on openregistry/assets/bounce/migration.py
> +        if related_lot_id is None:
Додав. Чомусь тут не відображається. Ось [коміт](https://github.com/openprocurement/openregistry.assets.bounce/pull/45/commits/74ec1474deb400938b93f7da7a8167b8789902bf).

2019-01-25 15:51 UTC, oleksiyVeretiuk approved these changes

2019-01-25 17:59 UTC, vmotso approved these changes

2019-01-28 08:43 UTC, Scandie approved these changes

2019-01-28 11:07 UTC, Leits commented on openregistry/assets/bounce/migration.py
> +        if related_lot_id is None:
Якщо тут немає, значить загальний патч змін не принесе ці зміни у кінцеву гілку

2019-01-28 11:07 UTC, Leits commented on openregistry/assets/bounce/migration.py
> +        if related_lot_id is None:
Але вони є, все ок :+1:

2019-01-28 11:16 UTC, leits approved these changes

2019-02-13 11:33 UTC, leits approved these changes

2019-02-13 12:01 UTC, merged